workflow cannot trigger another one
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

diff --git a/.github/workflows/pull-request-update-packages.yml b/.github/workflows/pull-request-update-packages.yml
--- a/.github/workflows/pull-request-update-packages.yml
+++ b/.github/workflows/pull-request-update-packages.yml
@@ -1,4 +1,4 @@
-name: pull-request-updated-package
+name: pull-request-update-packages
 
 on:
   pull_request:
@@ -35,6 +35,32 @@ jobs:
             echo "Invalid repository and branch to give pull request."
             exit 78;
         fi
+
+  BuildPackages:
+    needs: UpdatePackages
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+      os: [macos-latest, windows-latest, ubuntu-18.04]
+      include:
+        - os: windows-latest
+    steps:
+    - name: Checkout Repository
+      uses: actions/checkout@v1
+    - name: Inspect Payload
+      env:
+        TOKEN: ${{ secrets.GITHUB_TOKEN }}      
+      run: |
+        cat ${GITHUB_EVENT_PATH}
+        # TODO need to get the submodule updated name from the branch merged
+        sender=$(jq --raw-output .sender.login "${GITHUB_EVENT_PATH}")
+        echo "Sender is $sender"
+        label=$(jq --raw-output .pull_request.base.label "${GITHUB_EVENT_PATH}")
+        echo "Repository and branch to open pull request against is $label"
+        label_from=$(jq --raw-output .pull_request.head.label "${GITHUB_EVENT_PATH}")
+        echo "Repository and branch creating pull request: $label_from"
+        # Ensure that we fail so we can easily run again :)
+        exit 1;
     - name: Merge pull requests
       uses: pascalgn/automerge-action@v0.6.1
       env:
